version: '3.4'

services:
  music.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8000:80

  postgresql.data:
   environment:
    - POSTGRES_USER=music
    - POSTGRES_PASSWORD=music123
   logging:
      options:
        max-size: 10m
        max-file: "3"
   ports:
    - 5432:5432
   volumes:
    - ./postgres-data:/var/lib/postgresql/data

