version: '3.4'

services:
  music.api:
    image: music-api:${TAG:-latest}
    build:
      context: ../
      dockerfile: WebApi/Dockerfile
    depends_on:
      - postgresql.data
    container_name: music_api

  postgresql.data:
    image: postgres:14
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
